name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Проверка кода
      - uses: actions/checkout@v4

      # Установка Node.js
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Установка зависимостей
      - run: npm install

      # Сборка Nuxt-приложения для GitHub Pages
      - run: NUXT_APP_BASE_URL=/joki-joya/ npx nuxi generate

      # Деплой в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          publish_branch: gh-pages
